#!/bin/sh
export JEKYLL_VERSION=3.8
docker run --rm \
  --volume="$PWD:/srv/jekyll" \
  -p 4000:4000 -p 4001:4001 \
  -it jekyll/jekyll:$JEKYLL_VERSION \
  jekyll serve --livereload-port 4001 -wl --future
